import express from "express";
import category from "./category.js";
import tags from "./tags.js";
import product from "./product.js";
import user from "./user.js";
const router = express.Router();
router.use("/tags", tags);
router.use("/categories", category);
router.use("/products", product);
router.use("/", user);
export default router;
